// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOghlEJvc3xXYpHqloK8Tdb9HrrX3mSM',
    appId: '1:1051208311196:web:56e7b71921c2f65d9ee859',
    messagingSenderId: '1051208311196',
    projectId: 'iot-project-63373',
    authDomain: 'iot-project-63373.firebaseapp.com',
    storageBucket: 'iot-project-63373.appspot.com',
    measurementId: 'G-3EVGD4EG5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPu-qYZmfqFq5NzUIVhihzRFupQKcNH0',
    appId: '1:1051208311196:android:7494c8bb7b0b1cd69ee859',
    messagingSenderId: '1051208311196',
    projectId: 'iot-project-63373',
    storageBucket: 'iot-project-63373.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmrEt_02h9eGgVkm3Ym6GgxRqsuFXTpBI',
    appId: '1:1051208311196:ios:8e1139b0fb6896289ee859',
    messagingSenderId: '1051208311196',
    projectId: 'iot-project-63373',
    storageBucket: 'iot-project-63373.appspot.com',
    iosClientId: '1051208311196-7isd19r4foh3dfh113gt29gqu9bcj57d.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmrEt_02h9eGgVkm3Ym6GgxRqsuFXTpBI',
    appId: '1:1051208311196:ios:6d78f7cf3cdcaedf9ee859',
    messagingSenderId: '1051208311196',
    projectId: 'iot-project-63373',
    storageBucket: 'iot-project-63373.appspot.com',
    iosClientId: '1051208311196-vvg0hm9r06g41o3cnmlbaebjs1kg2nrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectFrontend.RunnerTests',
  );
}
